(function () {
  const boardEl = document.getElementById('chess-board');
  const messageEl = document.getElementById('chess-message');
  const glyphs = { K:'\u2654',Q:'\u2655',R:'\u2656',B:'\u2657',N:'\u2658',P:'\u2659',k:'\u265A',q:'\u265B',r:'\u265C',b:'\u265D',n:'\u265E',p:'\u265F' };
  const values = { p:100,n:320,b:330,r:500,q:900,k:20000 };
  const stats = { wins:0, draws:0, losses:0 };
  let level='medium', state, selected=null, options=[], locked=false, lastMove=null;
  const inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
  const white=p=>p&&p===p.toUpperCase();
  const color=p=>white(p)?'w':'b';
  const clone=s=>({board:s.board.map(row=>[...row]),turn:s.turn,castle:{...s.castle},ep:s.ep?[...s.ep]:null});
  function initial(){return{board:['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'].map(row=>[...row].map(x=>x==='.'?'':x)),turn:'w',castle:{K:true,Q:true,k:true,q:true},ep:null};}

  function attacked(s,r,c,by){
    const pawn=by==='w'?'P':'p', pawnRow=r+(by==='w'?1:-1); for(const dc of [-1,1])if(inside(pawnRow,c+dc)&&s.board[pawnRow][c+dc]===pawn)return true;
    const knight=by==='w'?'N':'n'; for(const [dr,dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])if(inside(r+dr,c+dc)&&s.board[r+dr][c+dc]===knight)return true;
    const king=by==='w'?'K':'k'; for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if((dr||dc)&&inside(r+dr,c+dc)&&s.board[r+dr][c+dc]===king)return true;
    for(const [dr,dc,types] of [[-1,0,'rq'],[1,0,'rq'],[0,-1,'rq'],[0,1,'rq'],[-1,-1,'bq'],[-1,1,'bq'],[1,-1,'bq'],[1,1,'bq']]){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){const p=s.board[rr][cc];if(p){if(color(p)===by&&types.includes(p.toLowerCase()))return true;break;}rr+=dr;cc+=dc;}}
    return false;
  }
  function inCheck(s,side){let kr=-1,kc=-1;const king=side==='w'?'K':'k';for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.board[r][c]===king){kr=r;kc=c;}return kr<0||attacked(s,kr,kc,side==='w'?'b':'w');}
  function pseudo(s,r,c){
    const p=s.board[r][c];if(!p)return[];const side=color(p), enemy=side==='w'?'b':'w', type=p.toLowerCase(), moves=[];
    const add=(rr,cc,special='')=>{if(!inside(rr,cc))return false;const target=s.board[rr][cc];if(!target){moves.push({from:[r,c],to:[rr,cc],special});return true;}if(color(target)===enemy)moves.push({from:[r,c],to:[rr,cc],special,capture:target});return false;};
    if(type==='p'){const dir=side==='w'?-1:1,start=side==='w'?6:1,promo=side==='w'?0:7;if(inside(r+dir,c)&&!s.board[r+dir][c]){moves.push({from:[r,c],to:[r+dir,c],promotion:r+dir===promo});if(r===start&&!s.board[r+2*dir][c])moves.push({from:[r,c],to:[r+2*dir,c],double:true});}for(const dc of [-1,1]){const rr=r+dir,cc=c+dc;if(inside(rr,cc)&&s.board[rr][cc]&&color(s.board[rr][cc])===enemy)moves.push({from:[r,c],to:[rr,cc],capture:s.board[rr][cc],promotion:rr===promo});else if(s.ep&&s.ep[0]===rr&&s.ep[1]===cc)moves.push({from:[r,c],to:[rr,cc],special:'ep',capture:side==='w'?'p':'P'});}return moves;}
    if(type==='n'){for(const [dr,dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);return moves;}
    if(type==='b'||type==='r'||type==='q'){const dirs=[];if(type!=='r')dirs.push([-1,-1],[-1,1],[1,-1],[1,1]);if(type!=='b')dirs.push([-1,0],[1,0],[0,-1],[0,1]);for(const[dr,dc]of dirs){let rr=r+dr,cc=c+dc;while(add(rr,cc)){rr+=dr;cc+=dc;}}return moves;}
    if(type==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);const row=side==='w'?7:0;if(r===row&&c===4&&!inCheck(s,side)){if(s.castle[side==='w'?'K':'k']&&!s.board[row][5]&&!s.board[row][6]&&s.board[row][7]===(side==='w'?'R':'r')&&!attacked(s,row,5,enemy)&&!attacked(s,row,6,enemy))moves.push({from:[r,c],to:[row,6],special:'castleK'});if(s.castle[side==='w'?'Q':'q']&&!s.board[row][1]&&!s.board[row][2]&&!s.board[row][3]&&s.board[row][0]===(side==='w'?'R':'r')&&!attacked(s,row,3,enemy)&&!attacked(s,row,2,enemy))moves.push({from:[r,c],to:[row,2],special:'castleQ'});}return moves;}
    return moves;
  }
  function apply(s,m){const n=clone(s),[fr,fc]=m.from,[tr,tc]=m.to,p=n.board[fr][fc],side=color(p),captured=n.board[tr][tc];n.board[fr][fc]='';n.board[tr][tc]=m.promotion?(side==='w'?'Q':'q'):p;if(m.special==='ep')n.board[fr][tc]='';if(m.special==='castleK'){n.board[tr][5]=n.board[tr][7];n.board[tr][7]='';}if(m.special==='castleQ'){n.board[tr][3]=n.board[tr][0];n.board[tr][0]='';}if(p==='K'){n.castle.K=false;n.castle.Q=false;}if(p==='k'){n.castle.k=false;n.castle.q=false;}if(fr===7&&fc===0)n.castle.Q=false;if(fr===7&&fc===7)n.castle.K=false;if(fr===0&&fc===0)n.castle.q=false;if(fr===0&&fc===7)n.castle.k=false;if(captured==='R'&&tr===7&&tc===0)n.castle.Q=false;if(captured==='R'&&tr===7&&tc===7)n.castle.K=false;if(captured==='r'&&tr===0&&tc===0)n.castle.q=false;if(captured==='r'&&tr===0&&tc===7)n.castle.k=false;n.ep=m.double?[(fr+tr)/2,fc]:null;n.turn=side==='w'?'b':'w';return n;}
  function legalMoves(s,side=s.turn){const moves=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(s.board[r][c]&&color(s.board[r][c])===side)for(const m of pseudo(s,r,c)){const n=apply(s,m);if(!inCheck(n,side))moves.push(m);}return moves;}
  function evaluate(s){let score=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++){const p=s.board[r][c];if(!p)continue;const center=(3.5-Math.abs(3.5-r))+(3.5-Math.abs(3.5-c));score+=(color(p)==='b'?1:-1)*(values[p.toLowerCase()]+center*2);}return score;}
  function search(s,depth,alpha,beta){const moves=legalMoves(s);if(!moves.length){if(inCheck(s,s.turn))return s.turn==='b'?-100000-depth:100000+depth;return 0;}if(!depth)return evaluate(s);if(s.turn==='b'){let best=-Infinity;for(const m of moves){best=Math.max(best,search(apply(s,m),depth-1,alpha,beta));alpha=Math.max(alpha,best);if(alpha>=beta)break;}return best;}let best=Infinity;for(const m of moves){best=Math.min(best,search(apply(s,m),depth-1,alpha,beta));beta=Math.min(beta,best);if(alpha>=beta)break;}return best;}
  function chooseAi(){const moves=legalMoves(state,'b');if(level==='easy')return moves[Math.floor(Math.random()*moves.length)];if(level==='medium'){const weighted=moves.map(m=>({m,score:(m.capture?values[m.capture.toLowerCase()]:0)+Math.random()*80})).sort((a,b)=>b.score-a.score);return weighted[0].m;}let best=-Infinity,bestMoves=[];for(const m of moves){const score=search(apply(state,m),2,-Infinity,Infinity);if(score>best){best=score;bestMoves=[m];}else if(score===best)bestMoves.push(m);}return bestMoves[Math.floor(Math.random()*bestMoves.length)];}
  function updateStats(){for(const k of Object.keys(stats))document.getElementById(k).textContent=String(stats[k]);window.scoreTracker?.notifyScore?.();}
  function status(){const moves=legalMoves(state);if(moves.length)return false;locked=true;if(inCheck(state,state.turn)){if(state.turn==='w'){stats.losses++;messageEl.textContent='Checkmate. The computer wins.';}else{stats.wins++;messageEl.textContent='Checkmate! You win.';}}else{stats.draws++;messageEl.textContent='Stalemate. The game is a draw.';}updateStats();return true;}
  function render(){boardEl.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const p=state.board[r][c],move=options.find(m=>m.to[0]===r&&m.to[1]===c),button=document.createElement('button');button.type='button';button.className=`chess-square ${(r+c)%2?'dark':''}${selected&&selected[0]===r&&selected[1]===c?' is-selected':''}${move?(p?' is-capture':' is-move'):''}${lastMove&&((lastMove.from[0]===r&&lastMove.from[1]===c)||(lastMove.to[0]===r&&lastMove.to[1]===c))?' last-move':''}`;button.textContent=glyphs[p]||'';button.setAttribute('aria-label',`${String.fromCharCode(97+c)}${8-r}${p?`, ${p}`:', empty'}`);button.addEventListener('click',()=>clickSquare(r,c));boardEl.appendChild(button);}}
  function clickSquare(r,c){if(locked||state.turn!=='w')return;const chosen=options.find(m=>m.to[0]===r&&m.to[1]===c);if(chosen){state=apply(state,chosen);lastMove=chosen;selected=null;options=[];render();if(status())return;locked=true;messageEl.textContent='Computer is thinking...';setTimeout(()=>{const ai=chooseAi();state=apply(state,ai);lastMove=ai;locked=false;render();if(!status())messageEl.textContent=inCheck(state,'w')?'Check. White to move.':'White to move.';},80);return;}const p=state.board[r][c];if(p&&color(p)==='w'){selected=[r,c];options=legalMoves(state,'w').filter(m=>m.from[0]===r&&m.from[1]===c);messageEl.textContent=options.length?'Choose a highlighted square.':'That piece has no legal moves.';}else{selected=null;options=[];messageEl.textContent='Select one of your white pieces.';}render();}
  function newGame(){state=initial();selected=null;options=[];lastMove=null;locked=false;messageEl.textContent='White to move.';render();}
  document.querySelectorAll('[data-level]').forEach(button=>button.addEventListener('click',()=>{level=button.dataset.level;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('is-selected',b===button));newGame();}));document.getElementById('chess-new').addEventListener('click',newGame);
  window.gameScoreApi={getScoreSnapshot:()=>({...stats}),applyScoreSnapshot(saved){for(const k of Object.keys(stats))stats[k]=Math.max(stats[k],Number(saved?.[k]||0));updateStats();}};
  window.chessGameTest={initial,legalMoves,apply,inCheck};
  newGame();
}());
